#!/usr/bin/env bash
set -eu

################################################################################
# Forbid spaces in indents.
################################################################################

readonly DEBUG=${DEBUG:-unset}
if [ "${DEBUG}" != unset ]; then
  set -x
fi

files_with_spaces_found=0
grep_params="-El"
if [[ "$1" = "-v" ]]; then
  # Verbose mode
  grep_params="-En"
  echo Verbose
  shift
fi

for file in "$@"; do
  if grep "$grep_params" '^ ' "$file"; then
    echo "Found space(s) within indentation in $file."
    echo
    files_with_spaces_found=$((files_with_spaces_found+1))
  fi
done

exit $files_with_spaces_found
